{sys_restart_syscall, "restart_syscall"}, // 0
{sys_exit, "exit"}, // 1
{sys_fork, "fork"}, // 2
{sys_read, "read"}, // 3
{sys_write, "write"}, // 4
{sys_open, "open"}, // 5
{sys_close, "close"}, // 6
{sys_waitpid, "waitpid"}, // 7
{sys_creat, "creat"}, // 8
{sys_link, "link"}, // 9
{sys_unlink, "unlink"}, // 10
{sys_execve, "execve"}, // 11
{sys_chdir, "chdir"}, // 12
{sys_time, "time"}, // 13
{sys_mknod, "mknod"}, // 14
{sys_chmod, "chmod"}, // 15
{sys_lchown, "lchown"}, // 16
{sys_break, "break"}, // 17
{sys_oldstat, "oldstat"}, // 18
{sys_lseek, "lseek"}, // 19
{sys_getpid, "getpid"}, // 20
{sys_mount, "mount"}, // 21
{sys_umount, "umount"}, // 22
{sys_setuid, "setuid"}, // 23
{sys_getuid, "getuid"}, // 24
{sys_stime, "stime"}, // 25
{sys_ptrace, "ptrace"}, // 26
{sys_alarm, "alarm"}, // 27
{sys_oldfstat, "oldfstat"}, // 28
{sys_pause, "pause"}, // 29
{sys_utime, "utime"}, // 30
{sys_stty, "stty"}, // 31
{sys_gtty, "gtty"}, // 32
{sys_access, "access"}, // 33
{sys_nice, "nice"}, // 34
{sys_ftime, "ftime"}, // 35
{sys_sync, "sync"}, // 36
{sys_kill, "kill"}, // 37
{sys_rename, "rename"}, // 38
{sys_mkdir, "mkdir"}, // 39
{sys_rmdir, "rmdir"}, // 40
{sys_dup, "dup"}, // 41
{sys_pipe, "pipe"}, // 42
{sys_times, "times"}, // 43
{sys_prof, "prof"}, // 44
{sys_brk, "brk"}, // 45
{sys_setgid, "setgid"}, // 46
{sys_getgid, "getgid"}, // 47
{sys_signal, "signal"}, // 48
{sys_geteuid, "geteuid"}, // 49
{sys_getegid, "getegid"}, // 50
{sys_acct, "acct"}, // 51
{sys_umount2, "umount2"}, // 52
{sys_lock, "lock"}, // 53
{sys_ioctl, "ioctl"}, // 54
{sys_fcntl, "fcntl"}, // 55
{sys_mpx, "mpx"}, // 56
{sys_setpgid, "setpgid"}, // 57
{sys_ulimit, "ulimit"}, // 58
{sys_oldolduname, "oldolduname"}, // 59
{sys_umask, "umask"}, // 60
{sys_chroot, "chroot"}, // 61
{sys_ustat, "ustat"}, // 62
{sys_dup2, "dup2"}, // 63
{sys_getppid, "getppid"}, // 64
{sys_getpgrp, "getpgrp"}, // 65
{sys_setsid, "setsid"}, // 66
{sys_sigaction, "sigaction"}, // 67
{sys_sgetmask, "sgetmask"}, // 68
{sys_ssetmask, "ssetmask"}, // 69
{sys_setreuid, "setreuid"}, // 70
{sys_setregid, "setregid"}, // 71
{sys_sigsuspend, "sigsuspend"}, // 72
{sys_sigpending, "sigpending"}, // 73
{sys_sethostname, "sethostname"}, // 74
{sys_setrlimit, "setrlimit"}, // 75
{sys_getrlimit, "getrlimit"}, // 76
{sys_getrusage, "getrusage"}, // 77
{sys_gettimeofday, "gettimeofday"}, // 78
{sys_settimeofday, "settimeofday"}, // 79
{sys_getgroups, "getgroups"}, // 80
{sys_setgroups, "setgroups"}, // 81
{sys_select, "select"}, // 82
{sys_symlink, "symlink"}, // 83
{sys_oldlstat, "oldlstat"}, // 84
{sys_readlink, "readlink"}, // 85
{sys_uselib, "uselib"}, // 86
{sys_swapon, "swapon"}, // 87
{sys_reboot, "reboot"}, // 88
{sys_readdir, "readdir"}, // 89
{sys_mmap, "mmap"}, // 90
{sys_munmap, "munmap"}, // 91
{sys_truncate, "truncate"}, // 92
{sys_ftruncate, "ftruncate"}, // 93
{sys_fchmod, "fchmod"}, // 94
{sys_fchown, "fchown"}, // 95
{sys_getpriority, "getpriority"}, // 96
{sys_setpriority, "setpriority"}, // 97
{sys_profil, "profil"}, // 98
{sys_statfs, "statfs"}, // 99
{sys_fstatfs, "fstatfs"}, // 100
{sys_ioperm, "ioperm"}, // 101
{sys_socketcall, "socketcall"}, // 102
{sys_syslog, "syslog"}, // 103
{sys_setitimer, "setitimer"}, // 104
{sys_getitimer, "getitimer"}, // 105
{sys_stat, "stat"}, // 106
{sys_lstat, "lstat"}, // 107
{sys_fstat, "fstat"}, // 108
{sys_olduname, "olduname"}, // 109
{sys_iopl, "iopl"}, // 110
{sys_vhangup, "vhangup"}, // 111
{sys_idle, "idle"}, // 112
{sys_vm86old, "vm86old"}, // 113
{sys_wait4, "wait4"}, // 114
{sys_swapoff, "swapoff"}, // 115
{sys_sysinfo, "sysinfo"}, // 116
{sys_ipc, "ipc"}, // 117
{sys_fsync, "fsync"}, // 118
{sys_sigreturn, "sigreturn"}, // 119
{sys_clone, "clone"}, // 120
{sys_setdomainname, "setdomainname"}, // 121
{sys_uname, "uname"}, // 122
{sys_modify_ldt, "modify_ldt"}, // 123
{sys_adjtimex, "adjtimex"}, // 124
{sys_mprotect, "mprotect"}, // 125
{sys_sigprocmask, "sigprocmask"}, // 126
{sys_create_module, "create_module"}, // 127
{sys_init_module, "init_module"}, // 128
{sys_delete_module, "delete_module"}, // 129
{sys_get_kernel_syms, "get_kernel_syms"}, // 130
{sys_quotactl, "quotactl"}, // 131
{sys_getpgid, "getpgid"}, // 132
{sys_fchdir, "fchdir"}, // 133
{sys_bdflush, "bdflush"}, // 134
{sys_sysfs, "sysfs"}, // 135
{sys_personality, "personality"}, // 136
{sys_afs_syscall, "afs_syscall"}, // 137
{sys_setfsuid, "setfsuid"}, // 138
{sys_setfsgid, "setfsgid"}, // 139
{sys__llseek, "_llseek"}, // 140
{sys_getdents, "getdents"}, // 141
{sys__newselect, "_newselect"}, // 142
{sys_flock, "flock"}, // 143
{sys_msync, "msync"}, // 144
{sys_readv, "readv"}, // 145
{sys_writev, "writev"}, // 146
{sys_getsid, "getsid"}, // 147
{sys_fdatasync, "fdatasync"}, // 148
{sys__sysctl, "_sysctl"}, // 149
{sys_mlock, "mlock"}, // 150
{sys_munlock, "munlock"}, // 151
{sys_mlockall, "mlockall"}, // 152
{sys_munlockall, "munlockall"}, // 153
{sys_sched_setparam, "sched_setparam"}, // 154
{sys_sched_getparam, "sched_getparam"}, // 155
{sys_sched_setscheduler, "sched_setscheduler"}, // 156
{sys_sched_getscheduler, "sched_getscheduler"}, // 157
{sys_sched_yield, "sched_yield"}, // 158
{sys_sched_get_priority_max, "sched_get_priority_max"}, // 159
{sys_sched_get_priority_min, "sched_get_priority_min"}, // 160
{sys_sched_rr_get_interval, "sched_rr_get_interval"}, // 161
{sys_nanosleep, "nanosleep"}, // 162
{sys_mremap, "mremap"}, // 163
{sys_setresuid, "setresuid"}, // 164
{sys_getresuid, "getresuid"}, // 165
{sys_vm86, "vm86"}, // 166
{sys_query_module, "query_module"}, // 167
{sys_poll, "poll"}, // 168
{sys_nfsservctl, "nfsservctl"}, // 169
{sys_setresgid, "setresgid"}, // 170
{sys_getresgid, "getresgid"}, // 171
{sys_prctl, "prctl"}, // 172
{sys_rt_sigreturn, "rt_sigreturn"}, // 173
{sys_rt_sigaction, "rt_sigaction"}, // 174
{sys_rt_sigprocmask, "rt_sigprocmask"}, // 175
{sys_rt_sigpending, "rt_sigpending"}, // 176
{sys_rt_sigtimedwait, "rt_sigtimedwait"}, // 177
{sys_rt_sigqueueinfo, "rt_sigqueueinfo"}, // 178
{sys_rt_sigsuspend, "rt_sigsuspend"}, // 179
{sys_pread64, "pread64"}, // 180
{sys_pwrite64, "pwrite64"}, // 181
{sys_chown, "chown"}, // 182
{sys_getcwd, "getcwd"}, // 183
{sys_capget, "capget"}, // 184
{sys_capset, "capset"}, // 185
{sys_sigaltstack, "sigaltstack"}, // 186
{sys_sendfile, "sendfile"}, // 187
{sys_getpmsg, "getpmsg"}, // 188
{sys_putpmsg, "putpmsg"}, // 189
{sys_vfork, "vfork"}, // 190
{sys_ugetrlimit, "ugetrlimit"}, // 191
{sys_mmap2, "mmap2"}, // 192
{sys_truncate64, "truncate64"}, // 193
{sys_ftruncate64, "ftruncate64"}, // 194
{sys_stat64, "stat64"}, // 195
{sys_lstat64, "lstat64"}, // 196
{sys_fstat64, "fstat64"}, // 197
{sys_lchown32, "lchown32"}, // 198
{sys_getuid32, "getuid32"}, // 199
{sys_getgid32, "getgid32"}, // 200
{sys_geteuid32, "geteuid32"}, // 201
{sys_getegid32, "getegid32"}, // 202
{sys_setreuid32, "setreuid32"}, // 203
{sys_setregid32, "setregid32"}, // 204
{sys_getgroups32, "getgroups32"}, // 205
{sys_setgroups32, "setgroups32"}, // 206
{sys_fchown32, "fchown32"}, // 207
{sys_setresuid32, "setresuid32"}, // 208
{sys_getresuid32, "getresuid32"}, // 209
{sys_setresgid32, "setresgid32"}, // 210
{sys_getresgid32, "getresgid32"}, // 211
{sys_chown32, "chown32"}, // 212
{sys_setuid32, "setuid32"}, // 213
{sys_setgid32, "setgid32"}, // 214
{sys_setfsuid32, "setfsuid32"}, // 215
{sys_setfsgid32, "setfsgid32"}, // 216
{sys_pivot_root, "pivot_root"}, // 217
{sys_mincore, "mincore"}, // 218
{sys_madvise, "madvise"}, // 219
{sys_getdents64, "getdents64"}, // 220
{sys_fcntl64, "fcntl64"}, // 221
{sys_none, NULL}, // 222
{sys_none, NULL}, // 223
{sys_gettid, "gettid"}, // 224
{sys_readahead, "readahead"}, // 225
{sys_setxattr, "setxattr"}, // 226
{sys_lsetxattr, "lsetxattr"}, // 227
{sys_fsetxattr, "fsetxattr"}, // 228
{sys_getxattr, "getxattr"}, // 229
{sys_lgetxattr, "lgetxattr"}, // 230
{sys_fgetxattr, "fgetxattr"}, // 231
{sys_listxattr, "listxattr"}, // 232
{sys_llistxattr, "llistxattr"}, // 233
{sys_flistxattr, "flistxattr"}, // 234
{sys_removexattr, "removexattr"}, // 235
{sys_lremovexattr, "lremovexattr"}, // 236
{sys_fremovexattr, "fremovexattr"}, // 237
{sys_tkill, "tkill"}, // 238
{sys_sendfile64, "sendfile64"}, // 239
{sys_futex, "futex"}, // 240
{sys_sched_setaffinity, "sched_setaffinity"}, // 241
{sys_sched_getaffinity, "sched_getaffinity"}, // 242
{sys_set_thread_area, "set_thread_area"}, // 243
{sys_get_thread_area, "get_thread_area"}, // 244
{sys_io_setup, "io_setup"}, // 245
{sys_io_destroy, "io_destroy"}, // 246
{sys_io_getevents, "io_getevents"}, // 247
{sys_io_submit, "io_submit"}, // 248
{sys_io_cancel, "io_cancel"}, // 249
{sys_fadvise64, "fadvise64"}, // 250
{sys_none, NULL}, // 251
{sys_exit_group, "exit_group"}, // 252
{sys_lookup_dcookie, "lookup_dcookie"}, // 253
{sys_epoll_create, "epoll_create"}, // 254
{sys_epoll_ctl, "epoll_ctl"}, // 255
{sys_epoll_wait, "epoll_wait"}, // 256
{sys_remap_file_pages, "remap_file_pages"}, // 257
{sys_set_tid_address, "set_tid_address"}, // 258
{sys_timer_create, "timer_create"}, // 259
{sys_timer_settime, "timer_settime"}, // 260
{sys_timer_gettime, "timer_gettime"}, // 261
{sys_timer_getoverrun, "timer_getoverrun"}, // 262
{sys_timer_delete, "timer_delete"}, // 263
{sys_clock_settime, "clock_settime"}, // 264
{sys_clock_gettime, "clock_gettime"}, // 265
{sys_clock_getres, "clock_getres"}, // 266
{sys_clock_nanosleep, "clock_nanosleep"}, // 267
{sys_statfs64, "statfs64"}, // 268
{sys_fstatfs64, "fstatfs64"}, // 269
{sys_tgkill, "tgkill"}, // 270
{sys_utimes, "utimes"}, // 271
{sys_fadvise64_64, "fadvise64_64"}, // 272
{sys_vserver, "vserver"}, // 273
{sys_mbind, "mbind"}, // 274
{sys_get_mempolicy, "get_mempolicy"}, // 275
{sys_set_mempolicy, "set_mempolicy"}, // 276
{sys_mq_open, "mq_open"}, // 277
{sys_mq_unlink, "mq_unlink"}, // 278
{sys_mq_timedsend, "mq_timedsend"}, // 279
{sys_mq_timedreceive, "mq_timedreceive"}, // 280
{sys_mq_notify, "mq_notify"}, // 281
{sys_mq_getsetattr, "mq_getsetattr"}, // 282
{sys_kexec_load, "kexec_load"}, // 283
{sys_waitid, "waitid"}, // 284
{sys_none, NULL}, // 285
{sys_add_key, "add_key"}, // 286
{sys_request_key, "request_key"}, // 287
{sys_keyctl, "keyctl"}, // 288
{sys_ioprio_set, "ioprio_set"}, // 289
{sys_ioprio_get, "ioprio_get"}, // 290
{sys_inotify_init, "inotify_init"}, // 291
{sys_inotify_add_watch, "inotify_add_watch"}, // 292
{sys_inotify_rm_watch, "inotify_rm_watch"}, // 293
{sys_migrate_pages, "migrate_pages"}, // 294
{sys_openat, "openat"}, // 295
{sys_mkdirat, "mkdirat"}, // 296
{sys_mknodat, "mknodat"}, // 297
{sys_fchownat, "fchownat"}, // 298
{sys_futimesat, "futimesat"}, // 299
{sys_fstatat64, "fstatat64"}, // 300
{sys_unlinkat, "unlinkat"}, // 301
{sys_renameat, "renameat"}, // 302
{sys_linkat, "linkat"}, // 303
{sys_symlinkat, "symlinkat"}, // 304
{sys_readlinkat, "readlinkat"}, // 305
{sys_fchmodat, "fchmodat"}, // 306
{sys_faccessat, "faccessat"}, // 307
{sys_pselect6, "pselect6"}, // 308
{sys_ppoll, "ppoll"}, // 309
{sys_unshare, "unshare"}, // 310
{sys_set_robust_list, "set_robust_list"}, // 311
{sys_get_robust_list, "get_robust_list"}, // 312
{sys_splice, "splice"}, // 313
{sys_sync_file_range, "sync_file_range"}, // 314
{sys_tee, "tee"}, // 315
{sys_vmsplice, "vmsplice"}, // 316
{sys_move_pages, "move_pages"}, // 317
{sys_getcpu, "getcpu"}, // 318
{sys_epoll_pwait, "epoll_pwait"}, // 319
{sys_utimensat, "utimensat"}, // 320
{sys_signalfd, "signalfd"}, // 321
{sys_timerfd_create, "timerfd_create"}, // 322
{sys_eventfd, "eventfd"}, // 323
{sys_fallocate, "fallocate"}, // 324
{sys_timerfd_settime, "timerfd_settime"}, // 325
{sys_timerfd_gettime, "timerfd_gettime"}, // 326
{sys_signalfd4, "signalfd4"}, // 327
{sys_eventfd2, "eventfd2"}, // 328
{sys_epoll_create1, "epoll_create1"}, // 329
{sys_dup3, "dup3"}, // 330
{sys_pipe2, "pipe2"}, // 331
{sys_inotify_init1, "inotify_init1"}, // 332
{sys_preadv, "preadv"}, // 333
{sys_pwritev, "pwritev"}, // 334
{sys_rt_tgsigqueueinfo, "rt_tgsigqueueinfo"}, // 335
{sys_perf_event_open, "perf_event_open"}, // 336
{sys_recvmmsg, "recvmmsg"}, // 337
{sys_fanotify_init, "fanotify_init"}, // 338
{sys_fanotify_mark, "fanotify_mark"}, // 339
{sys_prlimit64, "prlimit64"}, // 340
{sys_name_to_handle_at, "name_to_handle_at"}, // 341
{sys_open_by_handle_at, "open_by_handle_at"}, // 342
{sys_clock_adjtime, "clock_adjtime"}, // 343
{sys_syncfs, "syncfs"}, // 344
{sys_sendmmsg, "sendmmsg"}, // 345
{sys_setns, "setns"}, // 346
{sys_process_vm_readv, "process_vm_readv"}, // 347
{sys_process_vm_writev, "process_vm_writev"}, // 348
{sys_kcmp, "kcmp"}, // 349
{sys_finit_module, "finit_module"}, // 350
{sys_sched_setattr, "sched_setattr"}, // 351
{sys_sched_getattr, "sched_getattr"}, // 352
{sys_renameat2, "renameat2"}, // 353
{sys_seccomp, "seccomp"}, // 354
{sys_getrandom, "getrandom"}, // 355
{sys_memfd_create, "memfd_create"}, // 356
{sys_bpf, "bpf"}, // 357
{sys_execveat, "execveat"}, // 358
{sys_socket, "socket"}, // 359
{sys_socketpair, "socketpair"}, // 360
{sys_bind, "bind"}, // 361
{sys_connect, "connect"}, // 362
{sys_listen, "listen"}, // 363
{sys_accept4, "accept4"}, // 364
{sys_getsockopt, "getsockopt"}, // 365
{sys_setsockopt, "setsockopt"}, // 366
{sys_getsockname, "getsockname"}, // 367
{sys_getpeername, "getpeername"}, // 368
{sys_sendto, "sendto"}, // 369
{sys_sendmsg, "sendmsg"}, // 370
{sys_recvfrom, "recvfrom"}, // 371
{sys_recvmsg, "recvmsg"}, // 372
{sys_shutdown, "shutdown"}, // 373
{sys_userfaultfd, "userfaultfd"}, // 374
{sys_membarrier, "membarrier"}, // 375
{sys_mlock2, "mlock2"}, // 376
{sys_copy_file_range, "copy_file_range"}, // 377
{sys_preadv2, "preadv2"}, // 378
{sys_pwritev2, "pwritev2"}, // 379
{sys_pkey_mprotect, "pkey_mprotect"}, // 380
{sys_pkey_alloc, "pkey_alloc"}, // 381
{sys_pkey_free, "pkey_free"}, // 382
{sys_statx, "statx"}, // 383
{sys_arch_prctl, "arch_prctl"}, // 384
