{sys_read, "read"}, // 0
{sys_write, "write"}, // 1
{sys_open, "open"}, // 2
{sys_close, "close"}, // 3
{sys_stat, "stat"}, // 4
{sys_fstat, "fstat"}, // 5
{sys_lstat, "lstat"}, // 6
{sys_poll, "poll"}, // 7
{sys_lseek, "lseek"}, // 8
{sys_mmap, "mmap"}, // 9
{sys_mprotect, "mprotect"}, // 10
{sys_munmap, "munmap"}, // 11
{sys_brk, "brk"}, // 12
{sys_none, NULL}, // 13
{sys_rt_sigprocmask, "rt_sigprocmask"}, // 14
{sys_none, NULL}, // 15
{sys_none, NULL}, // 16
{sys_pread64, "pread64"}, // 17
{sys_pwrite64, "pwrite64"}, // 18
{sys_none, NULL}, // 19
{sys_none, NULL}, // 20
{sys_access, "access"}, // 21
{sys_pipe, "pipe"}, // 22
{sys_select, "select"}, // 23
{sys_sched_yield, "sched_yield"}, // 24
{sys_mremap, "mremap"}, // 25
{sys_msync, "msync"}, // 26
{sys_mincore, "mincore"}, // 27
{sys_madvise, "madvise"}, // 28
{sys_shmget, "shmget"}, // 29
{sys_shmat, "shmat"}, // 30
{sys_shmctl, "shmctl"}, // 31
{sys_dup, "dup"}, // 32
{sys_dup2, "dup2"}, // 33
{sys_pause, "pause"}, // 34
{sys_nanosleep, "nanosleep"}, // 35
{sys_getitimer, "getitimer"}, // 36
{sys_alarm, "alarm"}, // 37
{sys_setitimer, "setitimer"}, // 38
{sys_getpid, "getpid"}, // 39
{sys_sendfile, "sendfile"}, // 40
{sys_socket, "socket"}, // 41
{sys_connect, "connect"}, // 42
{sys_accept, "accept"}, // 43
{sys_sendto, "sendto"}, // 44
{sys_none, NULL}, // 45
{sys_none, NULL}, // 46
{sys_none, NULL}, // 47
{sys_shutdown, "shutdown"}, // 48
{sys_bind, "bind"}, // 49
{sys_listen, "listen"}, // 50
{sys_getsockname, "getsockname"}, // 51
{sys_getpeername, "getpeername"}, // 52
{sys_socketpair, "socketpair"}, // 53
{sys_none, NULL}, // 54
{sys_none, NULL}, // 55
{sys_clone, "clone"}, // 56
{sys_fork, "fork"}, // 57
{sys_vfork, "vfork"}, // 58
{sys_none, NULL}, // 59
{sys_exit, "exit"}, // 60
{sys_wait4, "wait4"}, // 61
{sys_kill, "kill"}, // 62
{sys_uname, "uname"}, // 63
{sys_semget, "semget"}, // 64
{sys_semop, "semop"}, // 65
{sys_semctl, "semctl"}, // 66
{sys_shmdt, "shmdt"}, // 67
{sys_msgget, "msgget"}, // 68
{sys_msgsnd, "msgsnd"}, // 69
{sys_msgrcv, "msgrcv"}, // 70
{sys_msgctl, "msgctl"}, // 71
{sys_fcntl, "fcntl"}, // 72
{sys_flock, "flock"}, // 73
{sys_fsync, "fsync"}, // 74
{sys_fdatasync, "fdatasync"}, // 75
{sys_truncate, "truncate"}, // 76
{sys_ftruncate, "ftruncate"}, // 77
{sys_getdents, "getdents"}, // 78
{sys_getcwd, "getcwd"}, // 79
{sys_chdir, "chdir"}, // 80
{sys_fchdir, "fchdir"}, // 81
{sys_rename, "rename"}, // 82
{sys_mkdir, "mkdir"}, // 83
{sys_rmdir, "rmdir"}, // 84
{sys_creat, "creat"}, // 85
{sys_link, "link"}, // 86
{sys_unlink, "unlink"}, // 87
{sys_symlink, "symlink"}, // 88
{sys_readlink, "readlink"}, // 89
{sys_chmod, "chmod"}, // 90
{sys_fchmod, "fchmod"}, // 91
{sys_chown, "chown"}, // 92
{sys_fchown, "fchown"}, // 93
{sys_lchown, "lchown"}, // 94
{sys_umask, "umask"}, // 95
{sys_gettimeofday, "gettimeofday"}, // 96
{sys_getrlimit, "getrlimit"}, // 97
{sys_getrusage, "getrusage"}, // 98
{sys_sysinfo, "sysinfo"}, // 99
{sys_times, "times"}, // 100
{sys_none, NULL}, // 101
{sys_getuid, "getuid"}, // 102
{sys_syslog, "syslog"}, // 103
{sys_getgid, "getgid"}, // 104
{sys_setuid, "setuid"}, // 105
{sys_setgid, "setgid"}, // 106
{sys_geteuid, "geteuid"}, // 107
{sys_getegid, "getegid"}, // 108
{sys_setpgid, "setpgid"}, // 109
{sys_getppid, "getppid"}, // 110
{sys_getpgrp, "getpgrp"}, // 111
{sys_setsid, "setsid"}, // 112
{sys_setreuid, "setreuid"}, // 113
{sys_setregid, "setregid"}, // 114
{sys_getgroups, "getgroups"}, // 115
{sys_setgroups, "setgroups"}, // 116
{sys_setresuid, "setresuid"}, // 117
{sys_getresuid, "getresuid"}, // 118
{sys_setresgid, "setresgid"}, // 119
{sys_getresgid, "getresgid"}, // 120
{sys_getpgid, "getpgid"}, // 121
{sys_setfsuid, "setfsuid"}, // 122
{sys_setfsgid, "setfsgid"}, // 123
{sys_getsid, "getsid"}, // 124
{sys_capget, "capget"}, // 125
{sys_capset, "capset"}, // 126
{sys_none, NULL}, // 127
{sys_none, NULL}, // 128
{sys_none, NULL}, // 129
{sys_rt_sigsuspend, "rt_sigsuspend"}, // 130
{sys_none, NULL}, // 131
{sys_utime, "utime"}, // 132
{sys_mknod, "mknod"}, // 133
{sys_none, NULL}, // 134
{sys_personality, "personality"}, // 135
{sys_ustat, "ustat"}, // 136
{sys_statfs, "statfs"}, // 137
{sys_fstatfs, "fstatfs"}, // 138
{sys_sysfs, "sysfs"}, // 139
{sys_getpriority, "getpriority"}, // 140
{sys_setpriority, "setpriority"}, // 141
{sys_sched_setparam, "sched_setparam"}, // 142
{sys_sched_getparam, "sched_getparam"}, // 143
{sys_sched_setscheduler, "sched_setscheduler"}, // 144
{sys_sched_getscheduler, "sched_getscheduler"}, // 145
{sys_sched_get_priority_max, "sched_get_priority_max"}, // 146
{sys_sched_get_priority_min, "sched_get_priority_min"}, // 147
{sys_sched_rr_get_interval, "sched_rr_get_interval"}, // 148
{sys_mlock, "mlock"}, // 149
{sys_munlock, "munlock"}, // 150
{sys_mlockall, "mlockall"}, // 151
{sys_munlockall, "munlockall"}, // 152
{sys_vhangup, "vhangup"}, // 153
{sys_modify_ldt, "modify_ldt"}, // 154
{sys_pivot_root, "pivot_root"}, // 155
{sys_none, NULL}, // 156
{sys_prctl, "prctl"}, // 157
{sys_arch_prctl, "arch_prctl"}, // 158
{sys_adjtimex, "adjtimex"}, // 159
{sys_setrlimit, "setrlimit"}, // 160
{sys_chroot, "chroot"}, // 161
{sys_sync, "sync"}, // 162
{sys_acct, "acct"}, // 163
{sys_settimeofday, "settimeofday"}, // 164
{sys_mount, "mount"}, // 165
{sys_umount2, "umount2"}, // 166
{sys_swapon, "swapon"}, // 167
{sys_swapoff, "swapoff"}, // 168
{sys_reboot, "reboot"}, // 169
{sys_sethostname, "sethostname"}, // 170
{sys_setdomainname, "setdomainname"}, // 171
{sys_iopl, "iopl"}, // 172
{sys_ioperm, "ioperm"}, // 173
{sys_none, NULL}, // 174
{sys_init_module, "init_module"}, // 175
{sys_delete_module, "delete_module"}, // 176
{sys_none, NULL}, // 177
{sys_none, NULL}, // 178
{sys_quotactl, "quotactl"}, // 179
{sys_none, NULL}, // 180
{sys_getpmsg, "getpmsg"}, // 181
{sys_putpmsg, "putpmsg"}, // 182
{sys_afs_syscall, "afs_syscall"}, // 183
{sys_tuxcall, "tuxcall"}, // 184
{sys_security, "security"}, // 185
{sys_gettid, "gettid"}, // 186
{sys_readahead, "readahead"}, // 187
{sys_setxattr, "setxattr"}, // 188
{sys_lsetxattr, "lsetxattr"}, // 189
{sys_fsetxattr, "fsetxattr"}, // 190
{sys_getxattr, "getxattr"}, // 191
{sys_lgetxattr, "lgetxattr"}, // 192
{sys_fgetxattr, "fgetxattr"}, // 193
{sys_listxattr, "listxattr"}, // 194
{sys_llistxattr, "llistxattr"}, // 195
{sys_flistxattr, "flistxattr"}, // 196
{sys_removexattr, "removexattr"}, // 197
{sys_lremovexattr, "lremovexattr"}, // 198
{sys_fremovexattr, "fremovexattr"}, // 199
{sys_tkill, "tkill"}, // 200
{sys_time, "time"}, // 201
{sys_futex, "futex"}, // 202
{sys_sched_setaffinity, "sched_setaffinity"}, // 203
{sys_sched_getaffinity, "sched_getaffinity"}, // 204
{sys_none, NULL}, // 205
{sys_none, NULL}, // 206
{sys_io_destroy, "io_destroy"}, // 207
{sys_io_getevents, "io_getevents"}, // 208
{sys_none, NULL}, // 209
{sys_io_cancel, "io_cancel"}, // 210
{sys_none, NULL}, // 211
{sys_lookup_dcookie, "lookup_dcookie"}, // 212
{sys_epoll_create, "epoll_create"}, // 213
{sys_none, NULL}, // 214
{sys_none, NULL}, // 215
{sys_remap_file_pages, "remap_file_pages"}, // 216
{sys_getdents64, "getdents64"}, // 217
{sys_set_tid_address, "set_tid_address"}, // 218
{sys_restart_syscall, "restart_syscall"}, // 219
{sys_semtimedop, "semtimedop"}, // 220
{sys_fadvise64, "fadvise64"}, // 221
{sys_none, NULL}, // 222
{sys_timer_settime, "timer_settime"}, // 223
{sys_timer_gettime, "timer_gettime"}, // 224
{sys_timer_getoverrun, "timer_getoverrun"}, // 225
{sys_timer_delete, "timer_delete"}, // 226
{sys_clock_settime, "clock_settime"}, // 227
{sys_clock_gettime, "clock_gettime"}, // 228
{sys_clock_getres, "clock_getres"}, // 229
{sys_clock_nanosleep, "clock_nanosleep"}, // 230
{sys_exit_group, "exit_group"}, // 231
{sys_epoll_wait, "epoll_wait"}, // 232
{sys_epoll_ctl, "epoll_ctl"}, // 233
{sys_tgkill, "tgkill"}, // 234
{sys_utimes, "utimes"}, // 235
{sys_none, NULL}, // 236
{sys_mbind, "mbind"}, // 237
{sys_set_mempolicy, "set_mempolicy"}, // 238
{sys_get_mempolicy, "get_mempolicy"}, // 239
{sys_mq_open, "mq_open"}, // 240
{sys_mq_unlink, "mq_unlink"}, // 241
{sys_mq_timedsend, "mq_timedsend"}, // 242
{sys_mq_timedreceive, "mq_timedreceive"}, // 243
{sys_none, NULL}, // 244
{sys_mq_getsetattr, "mq_getsetattr"}, // 245
{sys_none, NULL}, // 246
{sys_none, NULL}, // 247
{sys_add_key, "add_key"}, // 248
{sys_request_key, "request_key"}, // 249
{sys_keyctl, "keyctl"}, // 250
{sys_ioprio_set, "ioprio_set"}, // 251
{sys_ioprio_get, "ioprio_get"}, // 252
{sys_inotify_init, "inotify_init"}, // 253
{sys_inotify_add_watch, "inotify_add_watch"}, // 254
{sys_inotify_rm_watch, "inotify_rm_watch"}, // 255
{sys_migrate_pages, "migrate_pages"}, // 256
{sys_openat, "openat"}, // 257
{sys_mkdirat, "mkdirat"}, // 258
{sys_mknodat, "mknodat"}, // 259
{sys_fchownat, "fchownat"}, // 260
{sys_futimesat, "futimesat"}, // 261
{sys_newfstatat, "newfstatat"}, // 262
{sys_unlinkat, "unlinkat"}, // 263
{sys_renameat, "renameat"}, // 264
{sys_linkat, "linkat"}, // 265
{sys_symlinkat, "symlinkat"}, // 266
{sys_readlinkat, "readlinkat"}, // 267
{sys_fchmodat, "fchmodat"}, // 268
{sys_faccessat, "faccessat"}, // 269
{sys_pselect6, "pselect6"}, // 270
{sys_ppoll, "ppoll"}, // 271
{sys_unshare, "unshare"}, // 272
{sys_none, NULL}, // 273
{sys_none, NULL}, // 274
{sys_splice, "splice"}, // 275
{sys_tee, "tee"}, // 276
{sys_sync_file_range, "sync_file_range"}, // 277
{sys_none, NULL}, // 278
{sys_none, NULL}, // 279
{sys_utimensat, "utimensat"}, // 280
{sys_epoll_pwait, "epoll_pwait"}, // 281
{sys_signalfd, "signalfd"}, // 282
{sys_timerfd_create, "timerfd_create"}, // 283
{sys_eventfd, "eventfd"}, // 284
{sys_fallocate, "fallocate"}, // 285
{sys_timerfd_settime, "timerfd_settime"}, // 286
{sys_timerfd_gettime, "timerfd_gettime"}, // 287
{sys_accept4, "accept4"}, // 288
{sys_signalfd4, "signalfd4"}, // 289
{sys_eventfd2, "eventfd2"}, // 290
{sys_epoll_create1, "epoll_create1"}, // 291
{sys_dup3, "dup3"}, // 292
{sys_pipe2, "pipe2"}, // 293
{sys_inotify_init1, "inotify_init1"}, // 294
{sys_none, NULL}, // 295
{sys_none, NULL}, // 296
{sys_none, NULL}, // 297
{sys_perf_event_open, "perf_event_open"}, // 298
{sys_none, NULL}, // 299
{sys_fanotify_init, "fanotify_init"}, // 300
{sys_fanotify_mark, "fanotify_mark"}, // 301
{sys_prlimit64, "prlimit64"}, // 302
{sys_name_to_handle_at, "name_to_handle_at"}, // 303
{sys_open_by_handle_at, "open_by_handle_at"}, // 304
{sys_clock_adjtime, "clock_adjtime"}, // 305
{sys_syncfs, "syncfs"}, // 306
{sys_none, NULL}, // 307
{sys_setns, "setns"}, // 308
{sys_getcpu, "getcpu"}, // 309
{sys_none, NULL}, // 310
{sys_none, NULL}, // 311
{sys_kcmp, "kcmp"}, // 312
{sys_finit_module, "finit_module"}, // 313
{sys_sched_setattr, "sched_setattr"}, // 314
{sys_sched_getattr, "sched_getattr"}, // 315
{sys_renameat2, "renameat2"}, // 316
{sys_seccomp, "seccomp"}, // 317
{sys_getrandom, "getrandom"}, // 318
{sys_memfd_create, "memfd_create"}, // 319
{sys_kexec_file_load, "kexec_file_load"}, // 320
{sys_bpf, "bpf"}, // 321
{sys_none, NULL}, // 322
{sys_userfaultfd, "userfaultfd"}, // 323
{sys_membarrier, "membarrier"}, // 324
{sys_mlock2, "mlock2"}, // 325
{sys_copy_file_range, "copy_file_range"}, // 326
{sys_none, NULL}, // 327
{sys_none, NULL}, // 328
{sys_pkey_mprotect, "pkey_mprotect"}, // 329
{sys_pkey_alloc, "pkey_alloc"}, // 330
{sys_pkey_free, "pkey_free"}, // 331
{sys_statx, "statx"}, // 332
{sys_none, NULL}, // 332
{sys_none, NULL}, // 333
{sys_none, NULL}, // 334
{sys_none, NULL}, // 335
{sys_none, NULL}, // 336
{sys_none, NULL}, // 337
{sys_none, NULL}, // 338
{sys_none, NULL}, // 339
{sys_none, NULL}, // 340
{sys_none, NULL}, // 341
{sys_none, NULL}, // 342
{sys_none, NULL}, // 343
{sys_none, NULL}, // 344
{sys_none, NULL}, // 345
{sys_none, NULL}, // 346
{sys_none, NULL}, // 347
{sys_none, NULL}, // 348
{sys_none, NULL}, // 349
{sys_none, NULL}, // 350
{sys_none, NULL}, // 351
{sys_none, NULL}, // 352
{sys_none, NULL}, // 353
{sys_none, NULL}, // 354
{sys_none, NULL}, // 355
{sys_none, NULL}, // 356
{sys_none, NULL}, // 357
{sys_none, NULL}, // 358
{sys_none, NULL}, // 359
{sys_none, NULL}, // 360
{sys_none, NULL}, // 361
{sys_none, NULL}, // 362
{sys_none, NULL}, // 363
{sys_none, NULL}, // 364
{sys_none, NULL}, // 365
{sys_none, NULL}, // 366
{sys_none, NULL}, // 367
{sys_none, NULL}, // 368
{sys_none, NULL}, // 369
{sys_none, NULL}, // 370
{sys_none, NULL}, // 371
{sys_none, NULL}, // 372
{sys_none, NULL}, // 373
{sys_none, NULL}, // 374
{sys_none, NULL}, // 375
{sys_none, NULL}, // 376
{sys_none, NULL}, // 377
{sys_none, NULL}, // 378
{sys_none, NULL}, // 379
{sys_none, NULL}, // 380
{sys_none, NULL}, // 381
{sys_none, NULL}, // 382
{sys_none, NULL}, // 383
{sys_none, NULL}, // 384
{sys_none, NULL}, // 385
{sys_none, NULL}, // 386
{sys_none, NULL}, // 387
{sys_none, NULL}, // 388
{sys_none, NULL}, // 389
{sys_none, NULL}, // 390
{sys_none, NULL}, // 391
{sys_none, NULL}, // 392
{sys_none, NULL}, // 393
{sys_none, NULL}, // 394
{sys_none, NULL}, // 395
{sys_none, NULL}, // 396
{sys_none, NULL}, // 397
{sys_none, NULL}, // 398
{sys_none, NULL}, // 399
{sys_none, NULL}, // 400
{sys_none, NULL}, // 401
{sys_none, NULL}, // 402
{sys_none, NULL}, // 403
{sys_none, NULL}, // 404
{sys_none, NULL}, // 405
{sys_none, NULL}, // 406
{sys_none, NULL}, // 407
{sys_none, NULL}, // 408
{sys_none, NULL}, // 409
{sys_none, NULL}, // 410
{sys_none, NULL}, // 411
{sys_none, NULL}, // 412
{sys_none, NULL}, // 413
{sys_none, NULL}, // 414
{sys_none, NULL}, // 415
{sys_none, NULL}, // 416
{sys_none, NULL}, // 417
{sys_none, NULL}, // 418
{sys_none, NULL}, // 419
{sys_none, NULL}, // 420
{sys_none, NULL}, // 421
{sys_none, NULL}, // 422
{sys_none, NULL}, // 423
{sys_none, NULL}, // 424
{sys_none, NULL}, // 425
{sys_none, NULL}, // 426
{sys_none, NULL}, // 427
{sys_none, NULL}, // 428
{sys_none, NULL}, // 429
{sys_none, NULL}, // 430
{sys_none, NULL}, // 431
{sys_none, NULL}, // 432
{sys_none, NULL}, // 433
{sys_none, NULL}, // 434
{sys_none, NULL}, // 435
{sys_none, NULL}, // 436
{sys_none, NULL}, // 437
{sys_none, NULL}, // 438
{sys_none, NULL}, // 439
{sys_none, NULL}, // 440
{sys_none, NULL}, // 441
{sys_none, NULL}, // 442
{sys_none, NULL}, // 443
{sys_none, NULL}, // 444
{sys_none, NULL}, // 445
{sys_none, NULL}, // 446
{sys_none, NULL}, // 447
{sys_none, NULL}, // 448
{sys_none, NULL}, // 449
{sys_none, NULL}, // 450
{sys_none, NULL}, // 451
{sys_none, NULL}, // 452
{sys_none, NULL}, // 453
{sys_none, NULL}, // 454
{sys_none, NULL}, // 455
{sys_none, NULL}, // 456
{sys_none, NULL}, // 457
{sys_none, NULL}, // 458
{sys_none, NULL}, // 459
{sys_none, NULL}, // 460
{sys_none, NULL}, // 461
{sys_none, NULL}, // 462
{sys_none, NULL}, // 463
{sys_none, NULL}, // 464
{sys_none, NULL}, // 465
{sys_none, NULL}, // 466
{sys_none, NULL}, // 467
{sys_none, NULL}, // 468
{sys_none, NULL}, // 469
{sys_none, NULL}, // 470
{sys_none, NULL}, // 471
{sys_none, NULL}, // 472
{sys_none, NULL}, // 473
{sys_none, NULL}, // 474
{sys_none, NULL}, // 475
{sys_none, NULL}, // 476
{sys_none, NULL}, // 477
{sys_none, NULL}, // 478
{sys_none, NULL}, // 479
{sys_none, NULL}, // 480
{sys_none, NULL}, // 481
{sys_none, NULL}, // 482
{sys_none, NULL}, // 483
{sys_none, NULL}, // 484
{sys_none, NULL}, // 485
{sys_none, NULL}, // 486
{sys_none, NULL}, // 487
{sys_none, NULL}, // 488
{sys_none, NULL}, // 489
{sys_none, NULL}, // 490
{sys_none, NULL}, // 491
{sys_none, NULL}, // 492
{sys_none, NULL}, // 493
{sys_none, NULL}, // 494
{sys_none, NULL}, // 495
{sys_none, NULL}, // 496
{sys_none, NULL}, // 497
{sys_none, NULL}, // 498
{sys_none, NULL}, // 499
{sys_none, NULL}, // 500
{sys_none, NULL}, // 501
{sys_none, NULL}, // 502
{sys_none, NULL}, // 503
{sys_none, NULL}, // 504
{sys_none, NULL}, // 505
{sys_none, NULL}, // 506
{sys_none, NULL}, // 507
{sys_none, NULL}, // 508
{sys_none, NULL}, // 509
{sys_none, NULL}, // 510
{sys_none, NULL}, // 511
{sys_rt_sigaction, "rt_sigaction"}, // 512
{sys_rt_sigreturn, "rt_sigreturn"}, // 513
{sys_ioctl, "ioctl"}, // 514
{sys_readv, "readv"}, // 515
{sys_writev, "writev"}, // 516
{sys_recvfrom, "recvfrom"}, // 517
{sys_sendmsg, "sendmsg"}, // 518
{sys_recvmsg, "recvmsg"}, // 519
{sys_execve, "execve"}, // 520
{sys_ptrace, "ptrace"}, // 521
{sys_rt_sigpending, "rt_sigpending"}, // 522
{sys_rt_sigtimedwait, "rt_sigtimedwait"}, // 523
{sys_rt_sigqueueinfo, "rt_sigqueueinfo"}, // 524
{sys_sigaltstack, "sigaltstack"}, // 525
{sys_timer_create, "timer_create"}, // 526
{sys_mq_notify, "mq_notify"}, // 527
{sys_kexec_load, "kexec_load"}, // 528
{sys_waitid, "waitid"}, // 529
{sys_set_robust_list, "set_robust_list"}, // 530
{sys_get_robust_list, "get_robust_list"}, // 531
{sys_vmsplice, "vmsplice"}, // 532
{sys_move_pages, "move_pages"}, // 533
{sys_preadv, "preadv"}, // 534
{sys_pwritev, "pwritev"}, // 535
{sys_rt_tgsigqueueinfo, "rt_tgsigqueueinfo"}, // 536
{sys_recvmmsg, "recvmmsg"}, // 537
{sys_sendmmsg, "sendmmsg"}, // 538
{sys_process_vm_readv, "process_vm_readv"}, // 539
{sys_process_vm_writev, "process_vm_writev"}, // 540
{sys_setsockopt, "setsockopt"}, // 541
{sys_getsockopt, "getsockopt"}, // 542
{sys_io_setup, "io_setup"}, // 543
{sys_io_submit, "io_submit"}, // 544
{sys_execveat, "execveat"}, // 545
{sys_preadv2, "preadv2"}, // 546
{sys_pwritev2, "pwritev2"}, // 547
